### ISSUE TITLE
Crashes Immediately

### ISSUE THREAD

**Issue by lluxia** [NotAHero04/inventory-mod#1]
Hello,
I tried putting your mod on my server, and it immediately crashed my server upon firing it up with a critical error. The log can be found [here](https://mclo.gs/VzlFr8q) if it helps you.

Using: Fabric Loader 0.15.3, Minecraft Java 1.20.4
Mod Version: 0.9.0-beta.1

I'm mentioning the obvious, but I was on my server just before trying out your mod, and it worked fine after I removed your mod.

**Comment by NotAHero04** [comment]
The mod is only targeting clients for now. I don't have intention (and knowledge) to rewrite the mod with only server logic.
Thanks!
